### PR TITLE
Update 49 packages

### PR DESCRIPTION
**Pull request by Bisaloo**
:robot: This is an automated build

This will update 49 packages in your lesson with the following versions:

```
# NEW OR REMOVED PACKAGES -------------------------------
- MASS  [required by ggplot2]
- mgcv  [required by ggplot2]
- MASS   [7.3-60 -> *]
- mgcv   [1.9-0 -> *]
- nlme   [3.1-163 -> *]
- R      [4.3.1 -> 4.3.2]

# CRAN -----------------------------------------------------------------------
- brio          [1.1.3 -> 1.1.4]
- bslib         [0.5.1 -> 0.6.1]
- checkmate     [2.2.0 -> 2.3.1]
- cli           [3.6.1 -> 3.6.2]
- cpp11         [0.4.6 -> 0.4.7]
- data.table    [1.14.8 -> 1.14.10]
- desc          [1.4.2 -> 1.4.3]
- deSolve       [1.38 -> 1.40]
- dotCall64     [1.1-0 -> 1.1-1]
- dplyr         [1.1.3 -> 1.1.4]
- evaluate      [0.22 -> 0.23]
- fansi         [1.0.5 -> 1.0.6]
- haven         [2.5.3 -> 2.5.4]
- htmltools     [0.5.6.1 -> 0.5.7]
- htmlwidgets   [1.6.2 -> 1.6.4]
- igraph        [1.5.1 -> 1.6.0]
- jsonlite      [1.8.7 -> 1.8.8]
- knitr         [1.44 -> 1.45]
- lattice       [0.22-4 -> 0.22-5]
- lifecycle     [repo: RSPM -> CRAN; ver: 1.0.3 -> 1.0.4]
- maps          [3.4.1 -> 3.4.2]
- Matrix        [1.6-1.1 -> 1.6-4]
- pak           [0.6.0 -> 0.7.1]
- pkgbuild      [1.4.2 -> 1.4.3]
- processx      [3.8.2 -> 3.8.3]
- progress      [1.2.2 -> 1.2.3]
- RcppEigen     [0.3.3.9.3 -> 0.3.3.9.4]
- rlang         [1.1.1 -> 1.1.2]
- rprojroot     [2.0.3 -> 2.0.4]
- sass          [0.4.7 -> 0.4.8]
- scales        [1.2.1 -> 1.3.0]
- socialmixr    [0.3.0 -> 0.3.1]
- stringr       [repo: RSPM -> CRAN; ver: 1.5.0 -> 1.5.1]
- testthat      [3.2.0 -> 3.2.1]
- tinytex       [0.48 -> 0.49]
- vctrs         [0.6.4 -> 0.6.5]
- vroom         [1.6.4 -> 1.6.5]
- waldo         [0.5.1 -> 0.5.2]
- withr         [2.5.1 -> 2.5.2]
- xfun          [0.40 -> 0.41]
- yaml          [2.3.7 -> 2.3.8]
- MASS          [* -> 7.3-60]
- mgcv          [* -> 1.9-0]
- nlme          [* -> 3.1-164]

# GitHub ---------------------------------------------------------------------
- epidemics     [epiverse-trace/epidemics@HEAD: 6004c3a7 -> 5f6825d7]

# https://carpentries.r-universe.dev -----------------------------------------
- curl          [repo: CRAN -> https://carpentries.r-universe.dev; ver: 5.1.0 -> 5.2.0]
- ragg          [repo: RSPM -> https://carpentries.r-universe.dev; ver: 1.2.6 -> 1.2.7]
- stringi       [repo: CRAN -> https://carpentries.r-universe.dev; ver: 1.7.12 -> 1.8.3]
- xml2          [repo: CRAN -> https://carpentries.r-universe.dev; ver: 1.3.5 -> 1.3.6]

```

:stopwatch: In a few minutes, a comment will appear that will show you how the output has changed based on these updates.

If you want to inspect these changes locally, you can use the following code to check out a new branch:

```bash
git fetch origin update/packages
git checkout update/packages
```

- Auto-generated by [create-pull-request][1] on 2023-12-18

[1]: https://github.com/carpentries/create-pull-request/tree/main

### CODE REVIEW

**Comment by avallecam** [comment]
Fix #98

**Review by avallecam — APPROVED** [review]
ready to merge 🚀

**Comment by avallecam** [comment]
> Are you going to fix the epidemics version in a separate PR?

I appreciate that reminder.

I see two paths for this to fix {epidemics} and the [errors in the current online version](https://epiverse-trace.github.io/tutorials/simulating-transmission.html#introduction):

(1) Update the episodes to the most recent `{epidemics}` functions, plus updating the `renv.lock` (this may be the most time-demanding edit) or

(2) Keep the current version in the `renv.lock`:

https://github.com/epiverse-trace/tutorials/blob/215be1a16b37fcce990ae41b68de9736602a2ecb/renv/profiles/lesson-requirements/renv.lock#L562-L585

And replace the suggested installation:

https://github.com/epiverse-trace/tutorials/blob/215be1a16b37fcce990ae41b68de9736602a2ecb/episodes/simulating-transmission.Rmd#L152

Adding the tag version in it:

```r
pak::pak("epiverse-trace/epidemics@96a7b1457")
```

@Bisaloo, please let me know if there would be any additional (or fewer) steps to take this PR as an opportunity to fix {epidemics}.

@amanda-minter, can you do this fixing? It would depend on your time available.

**Comment by Bisaloo** [comment]
> (2) Keep the current version in the renv.lock:

I would be fine with this in theory and happy to opt for this option in the future so we don't necessarily have to always keep up to date with the very latest version of epidemics.

However, in this case, I suspect that different episodes were written with different versions of epidemics. This is my best guess to explain the error messages we currently have in the "Simulating transmission" episode.

So either we table this for now, merge this PR with a note that this needs to be resolved as soon as possible (either by using the epidemics version from `renv.lock` or the latest, I don't mind) or we tackle it in this PR.

**Comment by avallecam** [comment]
Let's try doing (2) to solve the website output. If this does not work, we'll proceed with (1) after this PR.

I identified that the maintainer can do (2) and the developer can do (1), so I'll add the version tag.

**Comment by avallecam** [comment]
@Bisaloo so, this should be ready to merge.

**Comment by Bisaloo** [comment]
Flagging that as per https://github.com/epiverse-trace/tutorials/commit/60db9e0072a918ac10714514c056a0ce81c07f7d, this is causing even more errors than previously.

**Comment by avallecam** [comment]
I'll do the merge.

I expect that removing the installation lines from the .Rmd files in this PR allow using the registered {epidemics} version in the renv.lock.

**Comment by avallecam** [comment]
> Flagging that as per [60db9e0](https://github.com/epiverse-trace/tutorials/commit/60db9e0072a918ac10714514c056a0ce81c07f7d), this is causing even more errors than previously.

@Bisaloo, thank you for flagging this. Errors do persist after merging option (2). This requires to do option (1) in a separate PR
 to solve this.

**Pull request merged**
